project_id = "uzmwskluglimwnkhdrkm"

[functions.bootstrap-tenant]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.toggle-student]
verify_jwt = false

[functions.reset-student-password]
verify_jwt = false